export const SIZES = {
  mbsmall: '8px',
  mbmedium: '12px',
  mblarge: '16px',
  mbxlarge: '20px',
  tbsmall: '12px',
  tbmedium: '16px',
  tblarge: '20px',
  tbxlarge: '24px',
  ltxsmall: '14px',
  ltsmall: '16px',
  ltmedium: '20px',
  ltlarge: '24px',
  ltxlarge: '28px',
  toolbar: '75px',
};
